import Head from 'next/head'
import { Button } from 'primereact/button'
import { useRouter } from 'next/router'

export default function Success() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>¡Transacción fallida!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="transaction-container">
        <h1>¡Transacción fallida!</h1>
        <p>
          No hemos procesado su pago con éxito. Por favor, inténtelo de nuevo.
        </p>
        <Button
          label="Intentar de nuevo"
          className="p-button-warning"
          onClick={() => {
            router.push('/app')
          }}
        />
      </div>
    </>
  )
}
