/* eslint-disable @typescript-eslint/no-unused-vars */
import Head from 'next/head'
import Header from '../../components/Header'
import { TransactionWrapper } from '../../components/TransactionWrapper'
import { withSSRAuth } from '../../utils/withSSRAuth'

export default function Login() {
  return (
    <>
      <Head>
        <title>Eurocambiovla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header />
        <TransactionWrapper />
      </div>
    </>
  )
}

export const getServerSideProps = withSSRAuth(async () => ({
  props: {}
}))
