import Head from 'next/head'
import Header from '../../components/Header'
import { TransactionWrapper } from '../../components/TransactionWrapper'

export default function Login() {
  return (
    <>
      <Head>
        <title>Eurocambiovla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header />
        <TransactionWrapper />
      </div>
    </>
  )
}
