import Head from 'next/head'
import { Button } from 'primereact/button'
import { useRouter } from 'next/router'

export default function Success() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>¡Transacción exitosa!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="transaction-container">
        <h1>¡Transacción exitosa!</h1>
        <p>
          Hemos procesado su pago con éxito y su remesa será procesada y enviada
          en breve.
        </p>
        <Button
          label="Ir al menú principal"
          className="p-button-success"
          onClick={() => {
            router.push('/app')
          }}
        />
      </div>
    </>
  )
}
