import Head from 'next/head'
import { LoginComponent } from '../components/LoginComponent'

import styles from '../styles/Login.module.css'

export default function Login() {
  return (
    <>
      <Head>
        <title>Eurocambiovla - Inicia sesión</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1 className={styles.containerLoginTitle}>
          ¡Bienvenido a Eurocambiovla!
        </h1>
        <main>
          <LoginComponent />
        </main>
      </div>
    </>
  )
}
