import { useEffect, useState } from 'react'
import Head from 'next/head'

import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { ProgressSpinner } from 'primereact/progressspinner';
import { parseISO } from 'date-fns'


import Header from '../components/Header'
import { Order, getMyOrders } from '../services/orders'

export default function OrderHistory() {
    const [loading, setLoading] = useState<boolean>(false)
    const [orders, setOrders] = useState<Array<Order>>([])


    async function handleGetOrders() {
        setLoading(true);
        try {
            let data = await getMyOrders();
            data = data.docs.map((o: Order) => {
                const object = {
                    ...o,
                    beneficiary: o.beneficiary.name,
                    totalToPay: `${o.totalToPay.toFixed(2)} ${o.pairRate.split('/', 1)[0]}`,
                    totalToReceive: `${o.totalToReceive.toFixed(2)} ${o.pairRate.split('/')[1]}`,
                    quantity: `${o.totalToReceive.toFixed(2)} ${o.pairRate.split('/', 1)[0]}`,
                    createdAt: parseISO(o.createdAt).toLocaleString("es-Es"),
                    updatedAt: parseISO(o.updatedAt).toLocaleString("es-Es")
                }

                return object
            })
            console.log(data,'orders')
            setOrders(data);
        } catch (e) {
            console.log(e);
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        handleGetOrders()
    }, [])

    useEffect(() => {
        console.log(orders)
    }, [orders])

    return (
        <>
            <Head>
                <title>Eurocambiovla - Historial</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <Header />
                <main style={{ display: 'flex', justifyContent: 'center' }}>
                    {loading ? (
                        <ProgressSpinner />
                    ) : (
                        <DataTable value={orders} scrollable style={{ overflowX: 'scroll' }} tableStyle={{ minWidth: '40rem' }} >
                            <Column field="createdAt" header="Fecha" style={{ width: '30%' }} />
                            <Column field="beneficiary" header="Destinatario" />
                            <Column field="quantity" header="Enviado" />
                            <Column field="totalToReceive" header="Rebido" />
                            <Column field="totalToPay" header="Pagado" />
                        </DataTable>
                    )}
                </main>
            </div>
        </>
    )
}
